INSERT INTO CUSTOMERS VALUES('A');
INSERT INTO CUSTOMERS VALUES('B');


INSERT INTO DEVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('WINDOWS', 4.0, true, 0);
INSERT INTO DEVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('MAC', 4.0, true, 1);


INSERT INTO SERVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('ANTIVIRUS-FOR-WINDOWS', 5.0, true, 0);
INSERT INTO SERVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('ANTIVIRUS-FOR-MAC', 7.0, true, 1);
INSERT INTO SERVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('BACKUP', 3.0, true, 2);
INSERT INTO SERVICES (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('SCREEN-SHARE', 1.0, true, 2);

