INSERT INTO CUSTOMER VALUES('A');
INSERT INTO CUSTOMER VALUES('B');


INSERT INTO DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('WINDOWS', 4.0, true, 0);
INSERT INTO DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('MAC', 4.0, true, 1);

INSERT INTO SERVICE_FOR_DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('ANTIVIRUS_FOR_WINDOWS', 5.0, true, 0);
INSERT INTO SERVICE_FOR_DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('ANTIVIRUS_FOR_MAC', 7.0, true, 1);
INSERT INTO SERVICE_FOR_DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('BACKUP', 3.0, true, 2);
INSERT INTO SERVICE_FOR_DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('PSA', 2.0, true, 2);
INSERT INTO SERVICE_FOR_DEVICE (ITEM, PRICE, AVAILABLE, COMPATIBILITY) VALUES('SCREEN_SHARE', 1.0, true, 2);


INSERT INTO DEVICES_PURCHASE (CUSTOMER_NAME, DEVICE_ITEM, PRICE) VALUES('B', 'MAC', 4.0);
INSERT INTO DEVICES_PURCHASE (CUSTOMER_NAME, DEVICE_ITEM, PRICE) VALUES('B', 'MAC', 4.0);
INSERT INTO DEVICES_PURCHASE (CUSTOMER_NAME, DEVICE_ITEM, PRICE) VALUES('B', 'WINDOWS', 4.0);
INSERT INTO DEVICES_PURCHASE (CUSTOMER_NAME, DEVICE_ITEM, PRICE) VALUES('A', 'MAC', 4.0);

INSERT INTO SERVICES_PURCHASE (DEVICE_PURCHASED_ID, HIRED_SERVICE_ITEM, PRICE) VALUES(1, 'ANTIVIRUS_FOR_MAC', 7.0);
INSERT INTO SERVICES_PURCHASE (DEVICE_PURCHASED_ID, HIRED_SERVICE_ITEM, PRICE) VALUES(2, 'ANTIVIRUS_FOR_MAC', 7.0);
INSERT INTO SERVICES_PURCHASE (DEVICE_PURCHASED_ID, HIRED_SERVICE_ITEM, PRICE) VALUES(2, 'BACKUP', 3.0);


/*
query for  join all services purchased in devices

SELECT CUSTOMER.NAME, DEVICES_PURCHASE.*, SERVICES_PURCHASE.*
FROM CUSTOMER
LEFT JOIN
DEVICES_PURCHASE ON DEVICES_PURCHASE.CUSTOMER_NAME = CUSTOMER.NAME
LEFT JOIN
SERVICES_PURCHASE ON DEVICES_PURCHASE.ID = SERVICES_PURCHASE.DEVICE_PURCHASED_ID

*/

